spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mobiletrain_mall
    username: root
    password: 123456


mybatis-plus:
  # 指定mappers路径
  #  mapper-locations: classpath:mappers/*.xml
  # 指定实体类路径
  type-aliases-package: cn.luxun.mall.entity
  configuration:
    # 开发时要用到控制台输出（StdOutImpl）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
